"""add_simulation_history

Revision ID: 92af1072f7ec
Revises: 7fc2c1dc17a0
Create Date: 2026-03-20 06:53:07.000086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92af1072f7ec'
down_revision: Union[str, Sequence[str], None] = '7fc2c1dc17a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user', sa.String(length=100), nullable=False),
    sa.Column('system_id', sa.String(length=20), nullable=False),
    sa.Column('system_name', sa.String(length=200), nullable=False),
    sa.Column('scenario_name', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('rto_target', sa.Float(), nullable=False),
    sa.Column('rto_estimated', sa.Float(), nullable=False),
    sa.Column('rto_met', sa.Integer(), nullable=False),
    sa.Column('rpo_target', sa.Float(), nullable=False),
    sa.Column('rpo_estimated', sa.Float(), nullable=False),
    sa.Column('rpo_met', sa.Integer(), nullable=False),
    sa.Column('overall_pass', sa.Integer(), nullable=False),
    sa.Column('dr_strategy', sa.String(length=100), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation_history')
    # ### end Alembic commands ###
